//
//  File.swift
//  
//
//  Created by Nuno Alves de Sousa on 09/05/2021.
//

import SwiftUI

public extension Emitter {
    /// - Parameters:
    ///   - particles: an array of type-erased views that will be randombly used by the emitter
    ///   - count: the number of particles generated by the emitter
    init<Particles>(particles: Particles, count: Int) where Particles: Collection, Particles.Element: View {
        self.particles = particles.map { $0.eraseToAnyView() }
        self.particleCount = count
    }
    
    /// - Parameters:
    ///   - images: an array of image filenames that will be randomly used by the emitter
    ///   - count: the number of particles generated by the emitter
    init(images: [String], count: Int) {
        self.particles = images.map { Image($0, bundle: .main).eraseToAnyView() }
        self.particleCount = count
    }
}
